---
# tasks file for roles/osp-instance-delete
- name: Delete OSP instances
  os_server:
    cloud: "{{ osp_cloud | default('openstack') }}"
    name: "{{ item.instance_name }}"
    state: absent
  loop: "{{ osp_servers }}"
