---
- hosts: workstation
  become: true
  gather_facts: false
  vars:
    credentials_file_path: /root/credential.rc
    order_script_file_path: /root/order_svc.sh
    common_script_file_path: /root/common.sh
  tasks:
    - name: create bin directory
      file:
        path: /root/bin
        state: directory

    - name: get script common.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/common.sh"
        dest: "{{ common_script_file_path }}"
        mode: 0755

    - name: get script jq
      get_url:
        url: "{{ param_repo_base }}/scripts/jq-linux64"
        dest: /root/bin/jq
        mode: 0755

    - name: get script order_svc.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/order_svc.sh"
        dest: "{{ order_script_file_path }}"
        mode: 0755

    - name: create credentials
      copy:
        content: |
          export username={{ param_user }}
          export password={{ param_password }}
          export uri=https://labs.opentlc.com
        dest: "{{ credentials_file_path }}"
        mode: 0755

    # Fix the existing shell scripts to reference jq command with bin/jq
    - name: fix scripts
      shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
      with_items:
        - "{{ common_script_file_path }}"
        - "{{ order_script_file_path }}"

    # Using this script will always deploy environments in the us-east-1 region.
    # TODO: this shell task is not working yet!
    - name: order service on opentlc
      shell: source "{{ credentials_file_path }}"; "{{ order_script_file_path }}" -y -c 'OPENTLC Automation' -i 'Ansible Advanced - Three Tier App' -t 1 -d 'dialog_expiration=7;region=na;nodes=1;dialog_runtime=8;notes=Training - As part of course'
      args:
        chdir: /root

    - name: Wait for mail
      pause:
        minutes: 10
