---
# tasks file for osp-facts

- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: r_os_servers

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    private_ip_address: "{{ item.private_v4 }}"
    group:
      - "{{ item.metadata.deployment_name }}"
      - "{{ item.metadata.group }}"
  with_items: "{{r_os_servers.openstack_servers}}"
