---
- name: Create Homework Assignment project
  tower_project:
    name: "{{proj_name}}"
    organization: "{{org_name}}"
    scm_update_on_launch: True
    scm_type: "git"
    scm_url: "{{scm_url}}"
    state: present

- name: Vault Credential for project secrets file decryption
  tower_credential:
    name: Homework Assignment vault password
    organization: Default
    state: present
    kind: vault
    tower_config_file: "{{tower_cli_file_path}}"
    vault_password: "{{vault_password}}"

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_config_file: "{{tower_cli_file_path}}"
    ssh_key_data: "/root/.ssh/openstack.pem"
    username: cloud-user

- name: Add tower inventory
  tower_inventory:
    name: "{{static_inventory_name}}"
    organization: "{{org_name}}"
    state: present
    tower_config_file: "{{tower_cli_file_path}}"

- name: Create Group in static inventory
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name "{{group_name}}"

- name: Create Group in static inventory
  tower_group:
    name: "{{group_name}}"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_config_file: "{{tower_cli_file_path}}"

- name: Add tower host
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_config_file: "{{tower_cli_file_path}}"

- name: Associate workstation host to group
  command: |
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Tower Creds key file
  tower_credential:
    name: "{{opentlc_cred_name}}"
    organization: Default
    state: present
    kind: ssh
    ssh_key_data: /root/.ssh/mykey.pem
    username: "{{opentlc_login}}"
    tower_config_file: "{{tower_cli_file_path}}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
...
