---
- name: Create job template workflow {{workflow_template_name}}
  tower_workflow_template:
    name: "{{workflow_template_name}}"
    organization: "{{org_name}}"
    schema: "{{ lookup('template', 'workflow.j2') }}"

...
